import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Navbar } from "@/components/navbar/navbar";
import FeatureFlagProvider from "@/components/providers/feature.flag.provider";
import flagsmith from "@flagsmith/flagsmith/isomorphic";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Comprez",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await flagsmith.init({
    environmentID: process.env.FLAGSMITH_KEY,
  });
  const serverState = flagsmith.getState();
  return (
    <html lang="en" suppressHydrationWarning className="h-dvh w-dvw">
      <body
        className={`${inter.variable} ${jetBrainsMono.variable} antialiased h-dvh w-dvw`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <div className="flex flex-col w-full h-full">
              <FeatureFlagProvider serverState={serverState}>
                <Navbar />
                {children}
              </FeatureFlagProvider>
            </div>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
